adding ceviche
FrontEndFoxes/kitchen-sune pull request #57
Opened 2022-09-22 01:44 UTC by TiffanyClark

2022-09-22 16:01 UTC, jlooper requested changes
just a few edits! I love ceviche

2022-09-22 16:01 UTC, jlooper commented on src/recipes/ceviche-with-shrimp.md
> +1 bag of cooked Shrimp
please make these and other lists bullet points to format well: 

- ingredient 1
- ingredient 2

2022-09-22 16:01 UTC, jlooper commented on src/recipes/ceviche-with-shrimp.md
> +Cut up the tomatoe, purple onion, jalpeno pepper, cilantro
Tomato (please check spelling)

2022-09-22 16:01 UTC, jlooper commented on src/recipes/ceviche-with-shrimp.md
> +To add a better taste, I also add lemon peper and garlic powder to add seasoning. you can add any kind of totilla chips to the dish.
looks yummy! you might add this either to the dinner category or let it stay in 'everything else'

2022-09-27 01:21 UTC, TiffanyClark commented
I made the correct changes for recipe

2022-10-01 03:18 UTC, jlooper approved these changes
going to merge this but edit a few things

2022-10-01 03:18 UTC, merged